apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: dailyhealer/web:1.0
        ports:
        - containerPort: 8000
        envFrom:
          - secretRef:
              name: web-env-secret
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: web
  type: LoadBalancer  # or NodePort for local testing
  ports:
  - protocol: TCP
    port: 80         # external port
    targetPort: 8000 # container port
